name: Test
on: pull_request
jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # @TODO npm caching
      # [#2] https://github.com/jmdejager/chuckle/issues/2

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Test
        run: npm run test:prod


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chuckle:pr-${{ github.event.pull_request.number }},
